# Form implementation generated from reading ui file 'D:\Python\pycharm\KTLT\ex127\MainWindow127.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 30, 651, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(70, 350, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonRefresh.setFont(font)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.pushButtonSortPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSortPrice.setGeometry(QtCore.QRect(290, 350, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonSortPrice.setFont(font)
        self.pushButtonSortPrice.setObjectName("pushButtonSortPrice")
        self.pushButtonReduce = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonReduce.setGeometry(QtCore.QRect(510, 350, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonReduce.setFont(font)
        self.pushButtonReduce.setObjectName("pushButtonReduce")
        self.pushButtonStatistic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStatistic.setGeometry(QtCore.QRect(70, 410, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonStatistic.setFont(font)
        self.pushButtonStatistic.setObjectName("pushButtonStatistic")
        self.pushButtonUSD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonUSD.setGeometry(QtCore.QRect(290, 410, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonUSD.setFont(font)
        self.pushButtonUSD.setObjectName("pushButtonUSD")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(510, 410, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(290, 460, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nguyễn Mai Thảo Linh"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh Data"))
        self.pushButtonSortPrice.setText(_translate("MainWindow", "Sort by Price"))
        self.pushButtonReduce.setText(_translate("MainWindow", "Reduce by Symbol"))
        self.pushButtonStatistic.setText(_translate("MainWindow", "Statistics"))
        self.pushButtonUSD.setText(_translate("MainWindow", "USD Column"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add New Row"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
